auto-provision: true
label: oid4vc

no-ledger: true

# Admin
admin: [ 0.0.0.0, 3001 ]
admin-insecure-mode: true
#admin-api-key: change-me

# Transport
inbound-transport:
  - [ http, 0.0.0.0, 3000 ]
  - [ ws, 0.0.0.0, 3002 ]
outbound-transport: http
endpoint:
  - http://host.docker.internal:3000

# plugins
plugin:
  - oid4vc
  - jwt_vc_json
  - sd_jwt_vc
  - mso_mdoc
  - status_list.v1_0


## Multi-tenancy
multitenant: true
jwt-secret: insecure-jwt-secret
multitenant-admin: true

# Wallet
wallet-name: ods_base_wallet
wallet-type: askar
wallet-storage-type: dpostgres_storage
wallet-key: prism_wallet_key
wallet-storage-config: '{"url":"postgres-db:5432"}'
wallet-storage-creds: '{"account":"postgres","password":"postgres","admin_account":"postgres","admin_password":"postgres"}'

# wallet-name: default
# wallet-type: askar
# wallet-storage-type: default
# wallet-key: "insecure"

log-level: info

# Connections
debug-connections: true
auto-accept-invites: true
auto-accept-requests: true
auto-ping-connection: true
auto-respond-messages: true